// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/course_category.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type XBlank struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *XBlank) Reset()         { *m = XBlank{} }
func (m *XBlank) String() string { return proto.CompactTextString(m) }
func (*XBlank) ProtoMessage()    {}
func (*XBlank) Descriptor() ([]byte, []int) {
	return fileDescriptor_fde79cb73866aac8, []int{0}
}

func (m *XBlank) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_XBlank.Unmarshal(m, b)
}
func (m *XBlank) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_XBlank.Marshal(b, m, deterministic)
}
func (m *XBlank) XXX_Merge(src proto.Message) {
	xxx_messageInfo_XBlank.Merge(m, src)
}
func (m *XBlank) XXX_Size() int {
	return xxx_messageInfo_XBlank.Size(m)
}
func (m *XBlank) XXX_DiscardUnknown() {
	xxx_messageInfo_XBlank.DiscardUnknown(m)
}

var xxx_messageInfo_XBlank proto.InternalMessageInfo

type Category struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Category) Reset()         { *m = Category{} }
func (m *Category) String() string { return proto.CompactTextString(m) }
func (*Category) ProtoMessage()    {}
func (*Category) Descriptor() ([]byte, []int) {
	return fileDescriptor_fde79cb73866aac8, []int{1}
}

func (m *Category) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Category.Unmarshal(m, b)
}
func (m *Category) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Category.Marshal(b, m, deterministic)
}
func (m *Category) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Category.Merge(m, src)
}
func (m *Category) XXX_Size() int {
	return xxx_messageInfo_Category.Size(m)
}
func (m *Category) XXX_DiscardUnknown() {
	xxx_messageInfo_Category.DiscardUnknown(m)
}

var xxx_messageInfo_Category proto.InternalMessageInfo

func (m *Category) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Category) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Category) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type CreateCategoryRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateCategoryRequest) Reset()         { *m = CreateCategoryRequest{} }
func (m *CreateCategoryRequest) String() string { return proto.CompactTextString(m) }
func (*CreateCategoryRequest) ProtoMessage()    {}
func (*CreateCategoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fde79cb73866aac8, []int{2}
}

func (m *CreateCategoryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCategoryRequest.Unmarshal(m, b)
}
func (m *CreateCategoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCategoryRequest.Marshal(b, m, deterministic)
}
func (m *CreateCategoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCategoryRequest.Merge(m, src)
}
func (m *CreateCategoryRequest) XXX_Size() int {
	return xxx_messageInfo_CreateCategoryRequest.Size(m)
}
func (m *CreateCategoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCategoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCategoryRequest proto.InternalMessageInfo

func (m *CreateCategoryRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateCategoryRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type CategoryList struct {
	Categories           []*Category `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CategoryList) Reset()         { *m = CategoryList{} }
func (m *CategoryList) String() string { return proto.CompactTextString(m) }
func (*CategoryList) ProtoMessage()    {}
func (*CategoryList) Descriptor() ([]byte, []int) {
	return fileDescriptor_fde79cb73866aac8, []int{3}
}

func (m *CategoryList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CategoryList.Unmarshal(m, b)
}
func (m *CategoryList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CategoryList.Marshal(b, m, deterministic)
}
func (m *CategoryList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CategoryList.Merge(m, src)
}
func (m *CategoryList) XXX_Size() int {
	return xxx_messageInfo_CategoryList.Size(m)
}
func (m *CategoryList) XXX_DiscardUnknown() {
	xxx_messageInfo_CategoryList.DiscardUnknown(m)
}

var xxx_messageInfo_CategoryList proto.InternalMessageInfo

func (m *CategoryList) GetCategories() []*Category {
	if m != nil {
		return m.Categories
	}
	return nil
}

type GetCategoryRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCategoryRequest) Reset()         { *m = GetCategoryRequest{} }
func (m *GetCategoryRequest) String() string { return proto.CompactTextString(m) }
func (*GetCategoryRequest) ProtoMessage()    {}
func (*GetCategoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fde79cb73866aac8, []int{4}
}

func (m *GetCategoryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCategoryRequest.Unmarshal(m, b)
}
func (m *GetCategoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCategoryRequest.Marshal(b, m, deterministic)
}
func (m *GetCategoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCategoryRequest.Merge(m, src)
}
func (m *GetCategoryRequest) XXX_Size() int {
	return xxx_messageInfo_GetCategoryRequest.Size(m)
}
func (m *GetCategoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCategoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCategoryRequest proto.InternalMessageInfo

func (m *GetCategoryRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterType((*XBlank)(nil), "pb._blank")
	proto.RegisterType((*Category)(nil), "pb.Category")
	proto.RegisterType((*CreateCategoryRequest)(nil), "pb.CreateCategoryRequest")
	proto.RegisterType((*CategoryList)(nil), "pb.CategoryList")
	proto.RegisterType((*GetCategoryRequest)(nil), "pb.GetCategoryRequest")
}

func init() { proto.RegisterFile("proto/course_category.proto", fileDescriptor_fde79cb73866aac8) }

var fileDescriptor_fde79cb73866aac8 = []byte{
	// 295 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0xc1, 0x4f, 0xab, 0x40,
	0x10, 0x87, 0xbb, 0xf4, 0xa5, 0xe9, 0x1b, 0x2a, 0x9a, 0x89, 0x1a, 0xd4, 0x0b, 0xd9, 0x78, 0xe0,
	0x60, 0x68, 0xd2, 0x1e, 0xf5, 0x24, 0x87, 0x5e, 0x34, 0x31, 0xed, 0xcd, 0x4b, 0xb3, 0xc0, 0xc4,
	0x6c, 0x6c, 0x01, 0x77, 0xb7, 0x26, 0xfe, 0xef, 0x1e, 0x0c, 0x6b, 0x21, 0x50, 0xd4, 0xdb, 0x64,
	0xe6, 0xc7, 0x37, 0xf3, 0x01, 0x70, 0x55, 0xaa, 0xc2, 0x14, 0xd3, 0xb4, 0xd8, 0x29, 0x4d, 0xeb,
	0x54, 0x18, 0x7a, 0x29, 0xd4, 0x47, 0x64, 0xbb, 0xe8, 0x94, 0x09, 0x1f, 0xc3, 0x68, 0x9d, 0x6c,
	0x44, 0xfe, 0xca, 0x9f, 0x60, 0x1c, 0xef, 0xe7, 0xe8, 0x81, 0x23, 0x33, 0x9f, 0x05, 0x2c, 0xfc,
	0xbf, 0x74, 0x64, 0x86, 0x08, 0xff, 0x72, 0xb1, 0x25, 0xdf, 0xb1, 0x1d, 0x5b, 0x63, 0x00, 0x6e,
	0x46, 0x3a, 0x55, 0xb2, 0x34, 0xb2, 0xc8, 0xfd, 0xa1, 0x1d, 0xb5, 0x5b, 0xfc, 0x11, 0xce, 0x62,
	0x45, 0xc2, 0x50, 0xcd, 0x5d, 0xd2, 0xdb, 0x8e, 0xb4, 0x69, 0x70, 0xec, 0x77, 0x9c, 0xd3, 0xc7,
	0xdd, 0xc1, 0xa4, 0x06, 0x3d, 0x48, 0x6d, 0xf0, 0x06, 0x60, 0x2f, 0x24, 0x49, 0xfb, 0x2c, 0x18,
	0x86, 0xee, 0x6c, 0x12, 0x95, 0x49, 0xd4, 0xac, 0x6b, 0xcd, 0xf9, 0x35, 0xe0, 0x82, 0xcc, 0xe1,
	0x25, 0x07, 0xa2, 0xb3, 0x4f, 0x06, 0xc7, 0x75, 0x66, 0x45, 0xea, 0x5d, 0xa6, 0x84, 0xb7, 0xe0,
	0x75, 0x35, 0xf0, 0xc2, 0x6e, 0xf9, 0x49, 0xed, 0xb2, 0x73, 0x00, 0x1f, 0xe0, 0x02, 0x4e, 0xbb,
	0xc1, 0x95, 0x51, 0x24, 0xb6, 0x7f, 0x21, 0x4e, 0xda, 0x88, 0xca, 0x94, 0x0f, 0x42, 0x86, 0x11,
	0x78, 0x55, 0x1d, 0x37, 0x46, 0x08, 0x55, 0xee, 0xfb, 0xe3, 0xf5, 0x9f, 0xc1, 0x39, 0xb8, 0x2d,
	0x5f, 0x3c, 0xaf, 0x02, 0xfd, 0x17, 0xd0, 0xbd, 0xf7, 0xfe, 0xe8, 0xd9, 0x95, 0xb9, 0x21, 0x95,
	0x8b, 0xcd, 0xb4, 0x4c, 0x92, 0x91, 0xfd, 0x4f, 0xe6, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x1d,
	0x29, 0x5d, 0x44, 0x46, 0x02, 0x00, 0x00,
}
